# Generated by Django 3.0.8 on 2020-08-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='firs_bid',
            new_name='first_bid',
        ),
        migrations.AddField(
            model_name='user',
            name='auctions_interest',
            field=models.ManyToManyField(blank=True, related_name='AuctionInterested', to='auctions.Auctions'),
        ),
        migrations.AddField(
            model_name='user',
            name='auctions_owner',
            field=models.ManyToManyField(blank=True, related_name='AuctionOwner', to='auctions.Auctions'),
        ),
    ]
