# Generated by Django 3.0.8 on 2020-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200801_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='auctions_interest',
            field=models.ManyToManyField(blank=True, related_name='auctionInterested', to='auctions.Auctions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auctions_owner',
            field=models.ManyToManyField(blank=True, related_name='auctionOwner', to='auctions.Auctions'),
        ),
        migrations.AddField(
            model_name='auctions',
            name='comments_in_auction',
            field=models.ManyToManyField(blank=True, related_name='auction', to='auctions.Comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments_owner',
            field=models.ManyToManyField(blank=True, related_name='commentOwner', to='auctions.Comments'),
        ),
    ]
