# Generated by Django 3.0.8 on 2020-08-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200801_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='auctions',
            name='comments_in_auction',
            field=models.ManyToManyField(blank=True, related_name='auctionComment', to='auctions.Comments'),
        ),
        migrations.AddField(
            model_name='auctions',
            name='bids_in_auction',
            field=models.ManyToManyField(blank=True, related_name='auctionBid', to='auctions.Bids'),
        ),
        migrations.AddField(
            model_name='user',
            name='bids_owner',
            field=models.ManyToManyField(blank=True, related_name='bidOwner', to='auctions.Bids'),
        ),
    ]
