# Generated by Django 3.0.8 on 2020-08-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200801_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
