# Generated by Django 3.0.8 on 2020-08-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
