# Generated by Django 3.0.8 on 2020-08-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200801_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='auction_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
