# Generated by Django 3.0.8 on 2020-08-03 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200801_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='auction_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
