# Generated by Django 3.0.8 on 2020-08-06 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctions_noticed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
